// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Metadata Metadata about entity creation.
type Metadata struct {
	// CreatedAt The date and time when the entity was created.
	CreatedAt time.Time `json:"createdAt"`
}

// Policy defines model for Policy.
type Policy struct {
	Action string `json:"action"`

	// Id The resource's unique identifier.
	Id *string `json:"id,omitempty"`

	// Metadata Metadata about entity creation.
	Metadata *Metadata `json:"metadata,omitempty"`
	Name     string    `json:"name"`
	Prefix   string    `json:"prefix"`

	// Time Number of days or ISO8601 duration
	Time string `json:"time"`
}

// PostPoliciesJSONRequestBody defines body for PostPolicies for application/json ContentType.
type PostPoliciesJSONRequestBody = Policy

// PutPoliciesIdJSONRequestBody defines body for PutPoliciesId for application/json ContentType.
type PutPoliciesIdJSONRequestBody = Policy

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all lifecycle policies
	// (GET /policies)
	GetPolicies(w http.ResponseWriter, r *http.Request)
	// Create a new lifecycle policy
	// (POST /policies)
	PostPolicies(w http.ResponseWriter, r *http.Request)
	// Delete a lifecycle policy by ID
	// (DELETE /policies/{id})
	DeletePoliciesId(w http.ResponseWriter, r *http.Request, id string)
	// Get a policy by ID
	// (GET /policies/{id})
	GetPoliciesId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a lifecycle policy by ID
	// (PUT /policies/{id})
	PutPoliciesId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all lifecycle policies
// (GET /policies)
func (_ Unimplemented) GetPolicies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new lifecycle policy
// (POST /policies)
func (_ Unimplemented) PostPolicies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a lifecycle policy by ID
// (DELETE /policies/{id})
func (_ Unimplemented) DeletePoliciesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a policy by ID
// (GET /policies/{id})
func (_ Unimplemented) GetPoliciesId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a lifecycle policy by ID
// (PUT /policies/{id})
func (_ Unimplemented) PutPoliciesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetPolicies operation middleware
func (siw *ServerInterfaceWrapper) GetPolicies(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostPolicies operation middleware
func (siw *ServerInterfaceWrapper) PostPolicies(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPolicies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeletePoliciesId operation middleware
func (siw *ServerInterfaceWrapper) DeletePoliciesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePoliciesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPoliciesId operation middleware
func (siw *ServerInterfaceWrapper) GetPoliciesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliciesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutPoliciesId operation middleware
func (siw *ServerInterfaceWrapper) PutPoliciesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPoliciesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/policies", wrapper.GetPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/policies", wrapper.PostPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/policies/{id}", wrapper.DeletePoliciesId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/policies/{id}", wrapper.GetPoliciesId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/policies/{id}", wrapper.PutPoliciesId)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RW3W/bNhD/V4jbgG2AFEuJ86W3rgYKA9sabPVT0YeTeKwZSCTDj6WCof99IGV7seU0",
	"3YBlbwJ5vLvfx529gUZ3RitS3kG1AdesqcP0+St55OgxfnNyjZXGS62g2t8wrHXwjJSXvmeNJYwBZ5CB",
	"sdqQ9ZJSpnRD/I2fpvqwJsbRE0PFmZcdscc1KebXtEv7iI5tE8TMQtsOPVQQX+XxBWTge0NQgfNWqs8w",
	"DBlYegjSEofq45Pyn/ahur6nxsOQwZ1uZdPHzg6bxmZscXOcPQPJTwOx5HSwDf3gWFDyIRCTPKIQkmzs",
	"nb5gZ9qYq7wUV9e3t2VeiMsyn5NocrxBnpMoRX1R4vymaCCiQP5etT1U3gbKpp10TzT63pKACr6b/a3o",
	"bCvnbK/lkIHCjk7CMpaE/HLyKvE8wfxb6GqyTAvGsXdMW7b84/3NVVEyHmzywovapGb2pbMd69uKU73i",
	"e6mETl1Kn8j8sJaOScfug/MMFdvSHPtaObLs7e+rBXtzt4QM/iTrxt7Ls+KsiNC0IYVGQgUX6SgDg36d",
	"LDAz0RtbP3ymZN9okQRtyaGCd+TvdjERmDNauTH+vCiS97XypNJTNKaVTXo8u3ejt0aB4pf01LmXdNya",
	"ddjzgtZiP9JyqM0v0vnIwB5CDHGh69D2u2tsW9ZKQU3ftPQkMgOj3Qm0d9odwn0I5PzPmvf/COm3ADz0",
	"SXT/MOG3/E+qHtN4QE+/W0VHdL5NpwyZosdjSvsUu/fSbCP5MM5SS56mLC/S+Y7nJU+OtNiRJ+ug+rgB",
	"GTuLLoXdNMeVdExY9gT88RB+mpA5n473BPvYMY8GmX/TA6U9EzqoY7pGiAwnVLG6Z8tFLPDSuJ3iZbqR",
	"lwv242q1XPwURyH+qIxlDpexqK9u+MUt5pfXxVV+WdbzvD6vz/Prel6L26YWBQrI/gXr+9+qEFLkyyoU",
	"r2DptBO3qjwjZAp5Trx35BlO9DLh1MII/hV8/P9uoVeTLBiOX5u+r4q2MuO/rGcnbhiGvwIAAP//mHac",
	"swwKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
