// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Metadata Metadata about entity creation.
type Metadata struct {
	// CreatedAt The date and time when the entity was created.
	CreatedAt time.Time `json:"createdAt"`
}

// Policy defines model for Policy.
type Policy struct {
	Action string `json:"action"`

	// Id The resource's unique identifier.
	Id *string `json:"id,omitempty"`

	// Metadata Metadata about entity creation.
	Metadata *Metadata `json:"metadata,omitempty"`
	Name     string    `json:"name"`
	Prefix   string    `json:"prefix"`

	// Time Number of days or ISO8601 duration
	Time string `json:"time"`
}

// PostPoliciesJSONRequestBody defines body for PostPolicies for application/json ContentType.
type PostPoliciesJSONRequestBody = Policy

// PutRulesIdJSONRequestBody defines body for PutRulesId for application/json ContentType.
type PutRulesIdJSONRequestBody = Policy

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all lifecycle policies
	// (GET /policies)
	GetPolicies(w http.ResponseWriter, r *http.Request)
	// Create a new lifecycle policy
	// (POST /policies)
	PostPolicies(w http.ResponseWriter, r *http.Request)
	// Delete a lifecycle policy by ID
	// (DELETE /rules/{id})
	DeleteRulesId(w http.ResponseWriter, r *http.Request, id string)
	// Get a user by ID
	// (GET /rules/{id})
	GetRulesId(w http.ResponseWriter, r *http.Request, id string)
	// Update a lifecycle policy by ID
	// (PUT /rules/{id})
	PutRulesId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all lifecycle policies
// (GET /policies)
func (_ Unimplemented) GetPolicies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new lifecycle policy
// (POST /policies)
func (_ Unimplemented) PostPolicies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a lifecycle policy by ID
// (DELETE /rules/{id})
func (_ Unimplemented) DeleteRulesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user by ID
// (GET /rules/{id})
func (_ Unimplemented) GetRulesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a lifecycle policy by ID
// (PUT /rules/{id})
func (_ Unimplemented) PutRulesId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetPolicies operation middleware
func (siw *ServerInterfaceWrapper) GetPolicies(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostPolicies operation middleware
func (siw *ServerInterfaceWrapper) PostPolicies(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPolicies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteRulesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteRulesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRulesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRulesId operation middleware
func (siw *ServerInterfaceWrapper) GetRulesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRulesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutRulesId operation middleware
func (siw *ServerInterfaceWrapper) PutRulesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutRulesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/policies", wrapper.GetPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/policies", wrapper.PostPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/rules/{id}", wrapper.DeleteRulesId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rules/{id}", wrapper.GetRulesId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/rules/{id}", wrapper.PutRulesId)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SWz0/jOhDH/xVr3pPeJaXJo/AgNx5IqNLuUrFwQhym8YQaJbbxj4Woyv++stN226YF",
	"9gB7i+zxeL6f+Y6VORSq1kqSdBbyOdhiRjXGz6/kkKPD8M3JFkZoJ5SEfLXDcKq8YySdcA0rDGEIOIAE",
	"tFGajBMUM8Ud4meun+pmRoyjI4aSMydqYs8zkszNaJn2GS1bJAiZS2VqdJBDODUIJyAB12iCHKwzQj5A",
	"2yZg6MkLQxzyu7Xr71ehavpIhYM2gYmqRNGEyjaLxqIrcb6dPQHBdwsxZJU3Bf1jmZfiyRMTPKgoBZlQ",
	"O71grauQKzsqj/87Pc0GaXmUDUZUFgM8QT6gMiunhxmOTtICggrkV7JqIHfGU9KvpF7r0d+GSsjhr+Gv",
	"jg4X7RyuetkmILGmnbK0oVK87NyKnHuav/l6SoapknFsLFOGjb9fnRynGePeRC+82ZtYzOrqZEl9cWO/",
	"X+G8kKWKVQoXYd7MhGXCskdvHUPJFphDXbeWDDu/vr1gZ5MxJPCDjO1qzw7SgzRIU5okagE5HMalBDS6",
	"WbTAUAdvLPzwQNG+wSJR2phDDpfkJsuYIMxqJW0X/2+aRu8r6UjGo6h1JYp4ePhoO291DQpfwlFt3+rj",
	"wqztigsag02HZbM3X4R1gcBKQgixvq7RNMttrCpWiZKKpqhoLTIBrewOtRNlN+U+ebLuf8Wb31L6HoGb",
	"Pgnub3t8sw+5dRvjBp5m+RRt4TyPqwyZpOdtpE2MHRpfkR3OBW+7QarIUR/xRVy/DrFjHr1osCZHxkJ+",
	"NwcRagr+hOUch8doG1WyJnt7/O57GEf9we6p7srlwRqjdx2QyrFSebkNqtPHsAeJTRs2vggX7Bu0T4WS",
	"foK34uO0gLSHawzZx/KSHEPmQ8gKnva75tZ/OLw/+xJ8Wre85vjaHLzar1vd/ens9X7btj8DAAD//yxL",
	"OrmQCQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
