{{- if .Values.monitoring.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{ include "app.labels" . | nindent 4 }}
    ionos.cloud/metrics: "true"
spec:
  podMetricsEndpoints:
    - port: metrics
      relabelings:
        - targetLabel: job
          replacement: {{ include "app.fullname" . }}
        - targetLabel: instance
          sourceLabels: [pod]
        - action: labelkeep
          regex: (job|instance|__.*)
  selector:
    matchLabels:
      {{ include "app.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    any: false
    matchNames:
      - {{ .Release.Namespace }}
{{- end -}}
