apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "app.name" . }}-alerting-rules
spec:
  groups:
    - name: {{ include "app.name" . }}-alerting-rules
      rules:
      {{- range $file, $_ := $.Files.Glob (printf "alerts/*.yaml") }}
      {{- if not (contains "_test" $file) }}
        - {{""}}{{- $.Files.Get $file | indent 10 | trim -}}
      {{- end }}
      {{- end }}