{{ $vaultPath := .Values.vaultPath }}
{{- $root := . -}}
{{ range .Values.image.pullExternalSecret }}
{{ if .enabled -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "app.labels" $root | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ "{{" }} .pullsecret | toString {{ "}}" }}"
    name: {{ .secretName }}
    creationPolicy: Owner
  data:
    - secretKey: pullsecret
      remoteRef:
        key: {{ $vaultPath }}/platform-s3/{{ .secretPath }}
{{ end }}
{{ end }}
